-- module schema update
CREATE TABLE IF NOT EXISTS `rm_daily_prices_config` (
  `name` varchar(50) NOT NULL,
  `value` varchar(255) NOT NULL,
  `metainfo` text NOT NULL,
  `order` tinyint(1) NOT NULL,
  PRIMARY KEY  (`name`)
) ENGINE=InnoDB CHARACTER SET 'utf8';

CREATE TABLE `rm_unit_daily_prices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `unit_id` int(11) NOT NULL DEFAULT '0',
  `period_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `start_datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `end_datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `weekly_rate` decimal(10,2) NOT NULL DEFAULT '0.00',
  `min_stay` int(11) NOT NULL DEFAULT '0',
  `max_stay` int(11) NOT NULL DEFAULT '0',
  `period_restriction` int(11) NOT NULL,
  `midweek_price` decimal(10,2) NOT NULL,
  `weekday_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `weekend_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `monthly_rate` decimal(10,2) NOT NULL DEFAULT '0.00',
  `number_persons` int(11) NOT NULL DEFAULT '1',
  `week_startday` tinyint(1) NOT NULL DEFAULT '-1',
  `week_startday1` tinyint(1) NOT NULL DEFAULT '-1',
  `week_endday` tinyint(1) NOT NULL DEFAULT '-1',
  `week_endday1` tinyint(1) NOT NULL DEFAULT '-1',
  PRIMARY KEY (`id`),
  KEY `unit_id` (`unit_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `rm_unit_daily_prices_config` (
  `name` varchar(50) NOT NULL,
  `unit_id` int(11) NOT NULL default '0',
  `value` varchar(255) NOT NULL,
  `order` tinyint(1) NOT NULL,
  PRIMARY KEY  (`name`,`unit_id`),
  KEY `unit_id` (`unit_id`)
) ENGINE=InnoDB CHARACTER SET 'utf8';

CREATE TABLE IF NOT EXISTS `rm_daily_prices_columns` (
  `name` varchar(255) NOT NULL,
  `label` varchar(255) NOT NULL,
  `admin_view` text NOT NULL,
  `enabled` tinyint(1) NOT NULL default '1',
  `order` tinyint(1) NOT NULL,
  PRIMARY KEY  (`name`)
) ENGINE=InnoDB CHARACTER SET 'utf8';

ALTER TABLE `rm_unit_daily_prices` ADD FOREIGN KEY (`unit_id`) REFERENCES `rm_units` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `rm_unit_daily_prices_config` ADD FOREIGN KEY ( `unit_id` ) REFERENCES `rm_units` (`id`) ON DELETE CASCADE ON UPDATE CASCADE ;

-- data
INSERT INTO `rm_daily_prices_config` (`name`, `value`, `metainfo`, `order`) VALUES('availablity_check', '1', '{view:{xtype:''combo'',id:''availablity_check'',fieldLabel:RM.Translate.Admin.DailyPrices.ConfigFields.AvailablityCheckEnabled,mode: ''local'',triggerAction: ''all'',hiddenName: ''availablity_check'',width: 180,store: [[0,RM.Translate.Common.OffLabel],[1, RM.Translate.Common.OnLabel]]},class_name: ''Ext.form.ComboBox''}', 0);
INSERT INTO `rm_daily_prices_config` (`name`, `value`, `metainfo`, `order`) VALUES('daily_price_enabled', '1', '{view: {xtype: ''combo'',id : ''daily_price_enabled'',fieldLabel: RM.Translate.Admin.DailyPrices.ConfigFields.DailyPriceEnabled,mode: ''local'',triggerAction: ''all'',hiddenName: ''daily_price_enabled'',width: 180,store: [[0, RM.Translate.Common.OffLabel],[1, RM.Translate.Common.OnLabel]]\r\n},class_name: ''Ext.form.ComboBox''}', 1);
INSERT INTO `rm_daily_prices_config` (`name`, `value`, `metainfo`, `order`) VALUES('default_end_time', '11:45', '{view:{xtype:"combo",id:"default_end_time",name:"default_end_time",hiddenName:"default_end_time",fieldLabel: RM.Translate.Admin.DailyPrices.ConfigFields.DefaultEndTime,width: 180,store: new Ext.data.SimpleStore({fields:[{name:''value'',type:''string''},{name:''text'',type:''string''}],data: RM.Common.TimeArray()}),forceSelection: true,mode: "local",triggerAction: ''all'',selectOnFocus: true,valueField: ''value'',displayField: ''text'',allowBlank: false},class_name: ''Ext.form.ComboBox''}', 7);
INSERT INTO `rm_daily_prices_config` (`name`, `value`, `metainfo`, `order`) VALUES('default_start_time', '12:00', '{view:{xtype:"combo",id:"default_start_time",name:"default_start_time",hiddenName:"default_start_time",fieldLabel: RM.Translate.Admin.DailyPrices.ConfigFields.DefaultStartTime,width: 180,store: new Ext.data.SimpleStore({fields:[{name:''value'',type:''string''},{name:''text'',type:''string''}],data: RM.Common.TimeArray()}),forceSelection: true,mode: "local",triggerAction: ''all'',selectOnFocus: true,valueField: ''value'',displayField: ''text'',allowBlank: false},class_name: ''Ext.form.ComboBox''}', 6);
INSERT INTO `rm_daily_prices_config` (`name`, `value`, `metainfo`, `order`) VALUES('midweek_days', '1,2,3', '{view: {xtype:''combo'',id : ''midweek_days'',hiddenName: ''midweek_days'',width: 180,fieldLabel: RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDays,mode: ''local'',triggerAction: ''all'',store: [["",RM.Translate.Admin.DailyPrices.ConfigFields.Disabled],["1,2,3,4,5",RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDaysMoTuWeThFr],["1,2,3,4", RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDaysMoTuWeTh],["1,2,3", RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDaysMoTuWe],["2,3,4,5",RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDaysTuWeThFr],["2,3,4",RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDaysTuWeTh],["2,3",RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDaysTuWe],["3,4,5",RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDaysWeThFr],["3,4",RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekDaysWeTh]]},class_name: ''Ext.form.ComboBox''}', 4);
INSERT INTO `rm_daily_prices_config` (`name`, `value`, `metainfo`, `order`) VALUES('monthly_price_enabled', '1', '{view: {xtype: ''combo'',id : ''monthly_price_enabled'',fieldLabel: RM.Translate.Admin.DailyPrices.ConfigFields.MonthlyPriceEnabled,mode: ''local'',triggerAction: ''all'',hiddenName: ''monthly_price_enabled'',	width: 180,store: [[0, RM.Translate.Common.OffLabel],[1, RM.Translate.Common.OnLabel]]},class_name: ''Ext.form.ComboBox''}', 3);
INSERT INTO `rm_daily_prices_config` (`name`, `value`, `metainfo`, `order`) VALUES('weekend_days', '6,0', '{view: {xtype:''combo'',id : ''weekend_days'',hiddenName: ''weekend_days'',width: 180,fieldLabel: RM.Translate.Admin.DailyPrices.ConfigFields.WeekendDays,mode: ''local'',triggerAction: ''all'',store: [["5,6",RM.Translate.Admin.DailyPrices.ConfigFields.WeekendDaysFriSat],["6,0", RM.Translate.Admin.DailyPrices.ConfigFields.WeekendDaysSatSun],["5,6,0", RM.Translate.Admin.DailyPrices.ConfigFields.WeekendDaysFriSatSun],["0", RM.Translate.Admin.DailyPrices.ConfigFields.WeekendDaysSun]]},class_name: ''Ext.form.ComboBox''}', 5);
INSERT INTO `rm_daily_prices_config` (`name`, `value`, `metainfo`, `order`) VALUES('weekend_price_enabled', '1', '{view: {xtype: ''combo'',id : ''weekend_price_enabled'',fieldLabel: RM.Translate.Admin.DailyPrices.ConfigFields.WeekendPriceEnabled,width: 180,mode: ''local'',triggerAction: ''all'',hiddenName: ''weekend_price_enabled'',store: [[0, RM.Translate.Common.OffLabel],[1, RM.Translate.Common.OnLabel]]},class_name: ''Ext.form.ComboBox''}', 2);

INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('end_datetime', 'RM.Translate.Admin.DailyPrices.Fields.EndDate', '{field: {id: "end_datetime", type: "date", name: "end_datetime",dateFormat: RM.Common.MySQLDateFormat}, column: {renderer: Ext.util.Format.dateRenderer(RM.Common.GUIDateFormat),dataIndex: "end_datetime", header: RM.Translate.Admin.DailyPrices.ConfigFields.EndDate,editor: new Ext.form.DateField({format: RM.Common.GUIDateFormat})}}', 1, 3);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('id', 'RM.Translate.Common.Id', '{field: {id: "id",name: "id"},column: {dataIndex: "id", header: RM.Translate.Common.Id}}', 1, 0);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('max_stay', 'RM.Translate.Admin.DailyPrices.Fields.MaxStay', '{field:{id: "max_stay",name: "max_stay"},column: {dataIndex: "max_stay",header: RM.Translate.Admin.DailyPrices.ConfigFields.MaxStay,renderer: function(value, metaData, record, rowIndex, colIndex, store) {for (var i = 0; i < RM.Common.DailyPrices_MaxStay.length; i++){if (RM.Common.DailyPrices_MaxStay[i][0] == value) return RM.Common.DailyPrices_MaxStay[i][1];}return value;},editor: new Ext.form.ComboBox({mode: ''local'',displayField: "value",triggerAction: ''all'',typeAhead: true,resizable: true,minListWidth: 220,store: new Ext.data.ArrayStore({idIndex: 0,fields: [''id'',''value''],data: RM.Common.DailyPrices_MaxStay})})}}', 1, 5);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('midweek_price', 'RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekRate', '{field: {id: "midweek_price", name: "midweek_price"}, column: { dataIndex: "midweek_price", header: RM.Translate.Admin.DailyPrices.ConfigFields.MidWeekRate, editor: new Ext.form.NumberField({allowBlank: false,allowNegative: false})}}', 1, 12);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('min_stay', 'RM.Translate.Admin.DailyPrices.Fields.MinStay', '{field:{id: "min_stay",name: "min_stay"},column: {dataIndex: "min_stay",header: RM.Translate.Admin.DailyPrices.ConfigFields.MinStay,renderer: function(value, metaData, record, rowIndex, colIndex, store) {for (var i = 0; i < RM.Common.DailyPrices_MinStay.length; i++){if (RM.Common.DailyPrices_MinStay[i][0] == value) return RM.Common.DailyPrices_MinStay[i][1];}return value;},editor: new Ext.form.ComboBox({mode: ''local'',displayField: "value",triggerAction: ''all'',typeAhead: true,resizable: true,minListWidth: 220,store: new Ext.data.ArrayStore({idIndex: 0,fields: [''id'',''value''],data: RM.Common.DailyPrices_MinStay})})}}', 1, 4);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('monthly_rate', 'RM.Translate.Admin.DailyPrices.ConfigFields.MonthlyRate', '{field: {id: "monthly_rate", name: "monthly_rate"}, column: { dataIndex: "monthly_rate", header: RM.Translate.Admin.DailyPrices.ConfigFields.MonthlyRate, editor: new Ext.form.NumberField({allowBlank: false,allowNegative: false})}}', 1, 15);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('period_name', 'RM.Translate.Admin.DailyPrices.Fields.PeriodName', '{field: {id: "period_name", name: "period_name"},column: {dataIndex: "period_name",header: RM.Translate.Admin.DailyPrices.ConfigFields.PeriodName,editor: new Ext.form.TextField({allowBlank: false})}}', 1, 1);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('period_restriction', 'RM.Translate.Admin.DailyPrices.ConfigFields.PeriodRestriction', '{field:{id: "period_restriction",name: "period_restriction"},column: {dataIndex: "period_restriction",header: RM.Translate.Admin.DailyPrices.ConfigFields.PeriodRestriction,renderer: function(value, metaData, record, rowIndex, colIndex, store) {for (var i = 0; i < 28; i=i+7){if (0 == value) return RM.Translate.Admin.DailyPrices.ConfigFields.Flexible;}return value;},editor: new Ext.form.ComboBox({mode: ''local'',displayField: "value",triggerAction: ''all'',typeAhead: true,resizable: true,minListWidth: 220,store: new Ext.data.ArrayStore({idIndex: 0,fields: [''id'',''value''],data:[[0,RM.Translate.Admin.DailyPrices.ConfigFields.Flexible],[7,"7"],[14,"14"],[21,"21"],[26,"28"]]})})}}', 1, 6);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('start_datetime', 'RM.Translate.Admin.DailyPrices.Fields.StartDate', '{field: {id: "start_datetime", type: "date", name: "start_datetime",dateFormat: RM.Common.MySQLDateFormat}, column: { renderer: Ext.util.Format.dateRenderer(RM.Common.GUIDateFormat),	dataIndex: "start_datetime", header: RM.Translate.Admin.DailyPrices.ConfigFields.StartDate, editor: new Ext.form.DateField({format: RM.Common.GUIDateFormat})}}', 1, 2);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('unit_id', '', '', 1, 0);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('weekday_price', 'RM.Translate.Admin.DailyPrices.Fields.WeekdayPrice', '{field: {id: "weekday_price", name: "weekday_price"},column: { dataIndex: "weekday_price",header: RM.Translate.Admin.DailyPrices.ConfigFields.WeekdayPrice, editor: new Ext.form.NumberField({allowBlank: false,allowNegative: false})}}', 1, 11);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('weekend_price', 'RM.Translate.Admin.DailyPrices.Fields.WeekendPrice', '{field: {id: "weekend_price",name: "weekend_price"}, column: {dataIndex: "weekend_price", header: RM.Translate.Admin.DailyPrices.ConfigFields.WeekendPrice,editor: new Ext.form.NumberField({allowBlank: false,allowNegative: false})}}', 1, 13);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('weekly_rate', 'RM.Translate.Admin.DailyPrices.Fields.WeeklyRate', '{field: {id: "weekly_rate", name: "weekly_rate"},column: { dataIndex: "weekly_rate", header: RM.Translate.Admin.DailyPrices.ConfigFields.WeeklyRate, editor: new Ext.form.NumberField({allowBlank: false,allowNegative: false})}}', 1, 14);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('week_endday', 'RM.Translate.Admin.DailyPrices.ConfigFields.EndDay', '{field:{id: "week_endday",name: "week_endday"},column: {dataIndex: "week_endday",header: RM.Translate.Admin.DailyPrices.ConfigFields.WeekEndDay,renderer: function(value, metaData, record, rowIndex, colIndex, store) {var WeekDays = RM.Translate.Common.JSON.PricingWeekDaysSelection;for (var i = 0; i < WeekDays.length; i++){if (WeekDays[i][0] == value) return WeekDays[i][1];}return value;},editor: new Ext.form.ComboBox({mode: ''local'',triggerAction: ''all'',resizable: true,minListWidth: 220,store: RM.Translate.Common.JSON.PricingWeekDaysSelection})}}', 1, 8);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('week_endday1', 'RM.Translate.Admin.DailyPrices.ConfigFields.EndDay1', '{field:{id: "week_endday1",name: "week_endday1"},column: {dataIndex: "week_endday1",header: RM.Translate.Admin.DailyPrices.ConfigFields.WeekEndDay1,renderer: function(value, metaData, record, rowIndex, colIndex, store) {var WeekDays = RM.Translate.Common.JSON.PricingWeekDaysSelection;for (var i = 0; i < WeekDays.length; i++){if (WeekDays[i][0] == value) return WeekDays[i][1];}return value;},editor: new Ext.form.ComboBox({mode: ''local'',triggerAction: ''all'',resizable: true,minListWidth: 220,store: RM.Translate.Common.JSON.PricingWeekDaysSelection})}}', 1, 10);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('week_startday', 'RM.Translate.Admin.DailyPrices.ConfigFields.WeekStartDay', '{field:{id: "week_startday",name: "week_startday"},column: {dataIndex: "week_startday",header: RM.Translate.Admin.DailyPrices.ConfigFields.WeekStartDay,renderer: function(value, metaData, record, rowIndex, colIndex, store) {var WeekDays = RM.Translate.Common.JSON.PricingWeekDaysSelection;for (var i = 0; i < WeekDays.length; i++){if (WeekDays[i][0] == value) return WeekDays[i][1];}return value;},editor: new Ext.form.ComboBox({mode: ''local'',triggerAction: ''all'',resizable: true,minListWidth: 220,store: RM.Translate.Common.JSON.PricingWeekDaysSelection})}}', 1, 7);
INSERT INTO `rm_daily_prices_columns` (`name`, `label`, `admin_view`, `enabled`, `order`) VALUES('week_startday1', 'RM.Translate.Admin.DailyPrices.ConfigFields.WeekStartDay1', '{field:{id: "week_startday1",name: "week_startday1"},column: {dataIndex: "week_startday1",header: RM.Translate.Admin.DailyPrices.ConfigFields.WeekStartDay1,renderer: function(value, metaData, record, rowIndex, colIndex, store) {var WeekDays = RM.Translate.Common.JSON.PricingWeekDaysSelection;for (var i = 0; i < WeekDays.length; i++){if (WeekDays[i][0] == value) return WeekDays[i][1];}return value;},editor: new Ext.form.ComboBox({mode: ''local'',triggerAction: ''all'',resizable: true,minListWidth: 220,store: RM.Translate.Common.JSON.PricingWeekDaysSelection})}}', 1, 9);
